version: '3'
services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./public:/usr/share/nginx/html
    depends_on:
      - api
  api:
    image: node:14
    working_dir: /app
    volumes:
      - ./api:/app
    command: npm start
    ports:
      - "3000:3000"
